server:
  port: 9090

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/Java8DemoDB"
    username: "postgres"
    password: "123456789"
    driver-class-name: "org.postgresql.Driver"

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true