server:
  port: 7070

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456789
    url: jdbc:postgresql://localhost:5432/SocialMediaAuthDB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: root

localhost:
  user-manager-url: http://localhost:8080/api/v1/user-profile